//
//  ChargingStationViewModel.swift
//  ChargeEasy
//
//  Created by Abdoulaye Yagmar Doumbia on 10/08/2024.
//

import Foundation
import Combine



class ChargingStationViewModel: ObservableObject {
    @Published var chargingStations: [ChargingStation] = []

    init() {
        loadMockData()
    }

    private func loadMockData() {
        // Simulation des données (Mock Data) pour les bornes de recharge
        let batteryCapacity = 75.0 // Capacité de la batterie en kWh (par exemple pour une Tesla Model 3)
        let currentBatteryLevel = 0.2 // 20% de batterie restante

        self.chargingStations = [
            // Stations à Paris
            ChargingStation(
                name: "Station 1",
                latitude: 48.8738,
                longitude: 2.2950,
                connectorTypes: [.CCS2],
                power: 50.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Située près de l'Arc de Triomphe, cette station offre une recharge rapide en courant continu avec une puissance de 50 kW.",
                rating: 4.8,
                reviews: ["Excellent emplacement, très rapide."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Place Charles de Gaulle, Paris",
                cost: 0.35,
                recentReview: "Super pratique, très rapide."
            ),
            ChargingStation(
                name: "Station 2",
                latitude: 48.8584,
                longitude: 2.2945,
                connectorTypes: [.Type2],
                power: 22.0,
                chargingType: .AC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Une station Type 2 située juste à côté de la Tour Eiffel, idéale pour une recharge lente en courant alternatif.",
                rating: 4.2,
                reviews: ["Vue imprenable, mais un peu lente."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Champ de Mars, Paris",
                cost: 0.25,
                recentReview: "Bonne expérience, mais la recharge prend du temps."
            ),
            ChargingStation(
                name: "Station 3",
                latitude: 48.8606,
                longitude: 2.3376,
                connectorTypes: [.CHAdeMO],
                power: 50.0,
                chargingType: .DC,
                isAvailable: false,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Profitez d'une recharge rapide en courant continu au Musée du Louvre avec cette borne CHAdeMO.",
                rating: 4.5,
                reviews: ["Rapide et facile, mais souvent occupée."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Musée du Louvre, Paris",
                cost: 0.30,
                recentReview: "Très pratique mais souvent occupée."
            ),
            ChargingStation(
                name: "Station 4",
                latitude: 48.8529,
                longitude: 2.3508,
                connectorTypes: [.Tesla],
                power: 120.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Rechargez rapidement votre véhicule Tesla près de Notre-Dame de Paris avec une puissance de 120 kW.",
                rating: 4.9,
                reviews: ["Très rapide et bien situé."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "6 Parvis Notre-Dame - Pl. Jean-Paul II, Paris",
                cost: 0.45,
                recentReview: "Très rapide et facile d'accès."
            ),
            ChargingStation(
                name: "Station 5",
                latitude: 48.8648,
                longitude: 2.3292,
                connectorTypes: [.CCS2],
                power: 150.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Station de recharge ultra-rapide près de l'Opéra Garnier, offrant une puissance de 150 kW en CCS2.",
                rating: 4.7,
                reviews: ["Incroyablement rapide!"],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Place de l'Opéra, Paris",
                cost: 0.50,
                recentReview: "Super expérience de recharge."
            ),
            ChargingStation(
                name: "Station 6",
                latitude: 48.8462,
                longitude: 2.3371,
                connectorTypes: [.Type2],
                power: 22.0,
                chargingType: .AC,
                isAvailable: false,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Rechargez votre véhicule électrique en courant alternatif au Jardin du Luxembourg.",
                rating: 4.3,
                reviews: ["Endroit agréable pour attendre la recharge."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Jardin du Luxembourg, Paris",
                cost: 0.28,
                recentReview: "Bonne recharge, bel endroit."
            ),
            ChargingStation(
                name: "Station 7",
                latitude: 48.8665,
                longitude: 2.3135,
                connectorTypes: [.CHAdeMO],
                power: 50.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Recharge rapide CHAdeMO disponible au Grand Palais.",
                rating: 4.6,
                reviews: ["Pratique pour visiter le Grand Palais."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Avenue Winston Churchill, Paris",
                cost: 0.32,
                recentReview: "Bon endroit pour une recharge rapide."
            ),
            ChargingStation(
                name: "Station 8",
                latitude: 48.8530,
                longitude: 2.3499,
                connectorTypes: [.Tesla],
                power: 120.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Recharge Tesla haute puissance sur l'Île de la Cité, au cœur de Paris.",
                rating: 4.8,
                reviews: ["Super rapide et facile d'accès."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Île de la Cité, Paris",
                cost: 0.45,
                recentReview: "Parfait pour une recharge rapide au centre de Paris."
            ),
            ChargingStation(
                name: "Station 9",
                latitude: 48.8721,
                longitude: 2.3018,
                connectorTypes: [.CCS2],
                power: 50.0,
                chargingType: .DC,
                isAvailable: false,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Station de recharge rapide CCS2 située sur les Champs-Élysées.",
                rating: 4.4,
                reviews: ["Pratique mais souvent bondée."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Avenue des Champs-Élysées, Paris",
                cost: 0.35,
                recentReview: "Bon emplacement, mais toujours occupé."
            ),
            ChargingStation(
                name: "Station 10",
                latitude: 48.8590,
                longitude: 2.3266,
                connectorTypes: [.Type2],
                power: 22.0,
                chargingType: .AC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Recharge en courant alternatif disponible à la Place de la Concorde.",
                rating: 4.5,
                reviews: ["Endroit agréable pour attendre."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Place de la Concorde, Paris",
                cost: 0.30,
                recentReview: "Bonne recharge, bel endroit."
            ),
            
            // Stations à San Francisco
            ChargingStation(
                name: "Station 11",
                latitude: 37.7749,
                longitude: -122.4194,
                connectorTypes: [.CCS2],
                power: 50.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Station de recharge rapide en courant continu au cœur de San Francisco.",
                rating: 4.7,
                reviews: ["Très pratique, bon emplacement."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Market Street, San Francisco",
                cost: 0.35,
                recentReview: "Parfait pour une recharge rapide."
            ),
            ChargingStation(
                name: "Station 12",
                latitude: 37.8087,
                longitude: -122.4098,
                connectorTypes: [.Type2],
                power: 22.0,
                chargingType: .AC,
                isAvailable: false,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Rechargez en courant alternatif près de Fisherman's Wharf.",
                rating: 4.3,
                reviews: ["Bonne recharge, endroit agréable."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Fisherman's Wharf, San Francisco",
                cost: 0.28,
                recentReview: "Recharge correcte, bonne localisation."
            ),
            ChargingStation(
                name: "Station 13",
                latitude: 37.7793,
                longitude: -122.4193,
                connectorTypes: [.Tesla],
                power: 120.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Recharge Tesla à haute puissance à Union Square.",
                rating: 4.9,
                reviews: ["Très rapide et bien situé."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Union Square, San Francisco",
                cost: 0.45,
                recentReview: "Super expérience, très rapide."
            ),
            ChargingStation(
                name: "Station 14",
                latitude: 37.8024,
                longitude: -122.4058,
                connectorTypes: [.CHAdeMO],
                power: 50.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Station CHAdeMO rapide à North Beach, San Francisco.",
                rating: 4.5,
                reviews: ["Recharge rapide, facile d'accès."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "North Beach, San Francisco",
                cost: 0.32,
                recentReview: "Bon endroit pour une recharge rapide."
            ),
            ChargingStation(
                name: "Station 15",
                latitude: 37.7648,
                longitude: -122.4630,
                connectorTypes: [.CCS2],
                power: 150.0,
                chargingType: .DC,
                isAvailable: false,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Recharge ultra-rapide au Golden Gate Park, parfaite pour les longs trajets.",
                rating: 4.8,
                reviews: ["Incroyablement rapide!"],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Golden Gate Park, San Francisco",
                cost: 0.50,
                recentReview: "Super expérience, très rapide."
            ),
            ChargingStation(
                name: "Station 16",
                latitude: 37.7936,
                longitude: -122.3958,
                connectorTypes: [.Type2],
                power: 22.0,
                chargingType: .AC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Recharge en courant alternatif à Embarcadero Center.",
                rating: 4.2,
                reviews: ["Bonne recharge, belle vue."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Embarcadero Center, San Francisco",
                cost: 0.28,
                recentReview: "Bonne recharge, bel endroit."
            ),
            ChargingStation(
                name: "Station 17",
                latitude: 37.7599,
                longitude: -122.4148,
                connectorTypes: [.Tesla],
                power: 120.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Station Tesla haute puissance dans le quartier Mission District.",
                rating: 4.7,
                reviews: ["Parfait pour une recharge rapide."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Mission District, San Francisco",
                cost: 0.45,
                recentReview: "Très rapide, très pratique."
            ),
            ChargingStation(
                name: "Station 18",
                latitude: 37.7955,
                longitude: -122.3937,
                connectorTypes: [.CHAdeMO],
                power: 50.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Recharge rapide CHAdeMO près de Ferry Building.",
                rating: 4.5,
                reviews: ["Très pratique, recharge rapide."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Ferry Building, San Francisco",
                cost: 0.32,
                recentReview: "Super recharge, bien situé."
            ),
            ChargingStation(
                name: "Station 19",
                latitude: 37.7338,
                longitude: -122.4467,
                connectorTypes: [.CCS2],
                power: 50.0,
                chargingType: .DC,
                isAvailable: true,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Station CCS2 dans le quartier de Sunset District.",
                rating: 4.3,
                reviews: ["Recharge facile, bonne localisation."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Sunset District, San Francisco",
                cost: 0.35,
                recentReview: "Bonne recharge, facile d'accès."
            ),
            ChargingStation(
                name: "Station 20",
                latitude: 37.8083,
                longitude: -122.4175,
                connectorTypes: [.Type2],
                power: 22.0,
                chargingType: .AC,
                isAvailable: false,
                batteryCapacity: batteryCapacity,
                currentBatteryLevel: currentBatteryLevel,
                description: "Recharge en courant alternatif à proximité du Pier 39.",
                rating: 4.4,
                reviews: ["Endroit agréable pour recharger."],
                imageURL: nil,
                lastUpdated: Date(),
                address: "Pier 39, San Francisco",
                cost: 0.28,
                recentReview: "Bonne recharge, bel endroit."
            )
        ]
    }
}
